### ISSUE TITLE
Suggestion: set an environment variable for authorization_endpoint_query_params setting

### ISSUE THREAD

**Issue by eviweb** [maicol07/laravel-oidc-client#6]
Hi @maicol07 ,
the setting `authorization_endpoint_query_params` is only settable in the `oidc.php` config file.
It hinders a fluid upgrade process when you want to publish an up to date config file with new options over an already existing config file.
Previous settings set directly in the config file are likely to be lost without a particular attention.
I suggest for this setting to create an environment variable `OIDC_AUTHORIZATION_ENDPOINT_QUERY_PARAMS` which can be configured with a coma separated list of key:value pairs.
Any opinion?
This is something I can address.

**Comment by maicol07** [comment]
I was thinking that too when I first added the setting. However, env doesn't support arrays.

One option would be: write a string array with a custom format and then parse it.

Second option: write a JSON that represent an array and then decode it.

Any suggestions?

**Comment by eviweb** [comment]
Hi @maicol07,
for now I would favour the option one with this format: `param1:value1,param2:value2,[...]`.
I would put a caveat on the colon, but can't think of any obvious cases where it would be a problem at the moment.
best

**Comment by maicol07** [comment]
> Hi @maicol07,
> for now I would favour the option one with this format: `param1:value1,param2:value2,[...]`.
> I would put a caveat on the colon, but can't think of any obvious cases where it would be a problem at the moment.
> best

Ok, I'll add it these days

**Comment by maicol07** [comment]
@eviweb this is finally done. Sorry for the wait, but I've been really busy.
However, it's now available in 2.3

**Comment by eviweb** [comment]
hi @maicol07,
many thanks for this enhancement and don't worry I'm also very busy ;).
Best
